const PRODUCTS = [
  {id:'cloud-swaddle',name:'Cloud Swaddle',age:'0-3 months',price:1299,icon:'☾',image:'assets/brand-board.png',pos:'15% 84%',desc:'A soft, breathable wrap designed for calm newborn settling.'},
  {id:'dream-sack',name:'Dream Zip Sleep Sack',age:'3-6 months',price:1799,icon:'☆',image:'assets/brand-board.png',pos:'50% 84%',desc:'An easy zip sleep sack for babies moving beyond the swaddle stage.'},
  {id:'moon-sleepwear',name:'Soft Moon Sleepwear',age:'6-12 months',price:1499,icon:'☁',image:'assets/homepage-reference.png',pos:'80% 24%',desc:'Gentle everyday sleepwear with a soft, relaxed fit.'},
  {id:'comfort-set',name:'Bedtime Comfort Set',age:'0-12 months',price:2299,icon:'✦',image:'assets/brand-board.png',pos:'84% 84%',desc:'A curated Hushly bedtime bundle for an easier evening routine.'}
];
const money = n => `₹${n.toLocaleString('en-IN')}`;
const getCart = () => JSON.parse(localStorage.getItem('hushlyCart') || '[]');
const saveCart = c => { localStorage.setItem('hushlyCart', JSON.stringify(c)); updateCount(); };
function updateCount(){ document.querySelectorAll('[data-cart-count]').forEach(el => el.textContent=getCart().reduce((s,x)=>s+x.qty,0)); }
function addToCart(id){ const c=getCart(); const row=c.find(x=>x.id===id); row?row.qty++:c.push({id,qty:1}); saveCart(c); showToast('Added to bag'); }
function showToast(msg){ let t=document.querySelector('.toast'); if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)} t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500); }
function productCard(p){return `<article class="card"><a class="card-link" href="product.html?id=${p.id}"><div class="visual product-photo"><img src="${p.image}" alt="${p.name}" style="object-position:${p.pos}"></div><div class="body"><h3>${p.name}</h3><small>${p.age}</small><p>${p.desc}</p><p class="price">${money(p.price)}</p></div></a><button class="add" data-add="${p.id}">Add to Bag</button></article>`}
function renderProducts(){ const grid=document.querySelector('#products'); if(grid) grid.innerHTML=PRODUCTS.map(productCard).join(''); }
function renderProduct(){ const host=document.querySelector('#productDetail'); if(!host)return; const id=new URLSearchParams(location.search).get('id')||PRODUCTS[0].id; const p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0]; document.title=`${p.name} — Hushly`; host.innerHTML=`<div class="pdp-art"><img src="${p.image}" alt="${p.name}" style="object-position:${p.pos}"></div><div class="pdp-copy"><p class="eyebrow">HUSHLY • ${p.age.toUpperCase()}</p><h1>${p.name}</h1><p class="pdp-price">${money(p.price)}</p><p>${p.desc}</p><div class="trust-box"><b>Designed for clearer choices</b><span>Breathable, comfort-led materials</span><span>Clear age and use guidance</span><span>Easy-care instructions</span></div><button class="cta button" data-add="${p.id}">Add to Bag — ${money(p.price)}</button><details open><summary>Product details</summary><p>Soft-touch construction, simple care and a calm Hushly design. Academic prototype product.</p></details><details><summary>Safety & use</summary><p>Use only as intended and select the correct size/stage. Follow the product instructions and current safe-sleep guidance relevant to your child.</p></details></div>`; }
function renderCart(){ const host=document.querySelector('#cartPage'); if(!host)return; const c=getCart(); if(!c.length){host.innerHTML='<div class="empty"><h2>Your bag is empty</h2><p>Choose a bedtime essential to get started.</p><a class="cta" href="shop.html">Shop products →</a></div>';return;} let total=0; host.innerHTML=c.map(row=>{const p=PRODUCTS.find(x=>x.id===row.id);total+=p.price*row.qty;return `<div class="cart-line"><div class="mini-art"><img src="${p.image}" alt="${p.name}" style="object-position:${p.pos}"></div><div><a href="product.html?id=${p.id}"><b>${p.name}</b></a><small>${p.age}</small><div class="qty"><button data-qty="${p.id}" data-delta="-1">−</button><span>${row.qty}</span><button data-qty="${p.id}" data-delta="1">+</button></div></div><b>${money(p.price*row.qty)}</b><button class="remove" data-remove="${p.id}">Remove</button></div>`}).join('')+`<div class="summary"><span>Subtotal</span><b>${money(total)}</b><p>Shipping calculated at checkout. Free above ₹999.</p><a class="cta checkout-link" href="checkout.html">Continue to Checkout →</a></div>`; }
function renderCheckout(){ const totalEl=document.querySelector('#checkoutTotal'); if(!totalEl)return; const c=getCart(); const total=c.reduce((s,row)=>{const p=PRODUCTS.find(x=>x.id===row.id);return s+(p?p.price*row.qty:0)},0); totalEl.textContent=money(total); const form=document.querySelector('#checkoutForm'); form.addEventListener('submit',e=>{e.preventDefault();localStorage.removeItem('hushlyCart');document.querySelector('.checkout-wrap').innerHTML='<div class="success"><div class="success-icon">✓</div><h1>Prototype order complete</h1><p>Your checkout flow works. No real payment has been taken.</p><a class="cta" href="index.html">Back to Hushly</a></div>';updateCount();}); }
document.addEventListener('click',e=>{ const add=e.target.closest('[data-add]'); if(add){e.preventDefault();addToCart(add.dataset.add)} const q=e.target.closest('[data-qty]');if(q){const c=getCart(),r=c.find(x=>x.id===q.dataset.qty);if(r){r.qty+=Number(q.dataset.delta);if(r.qty<=0)c.splice(c.indexOf(r),1);saveCart(c);renderCart()}} const rem=e.target.closest('[data-remove]');if(rem){saveCart(getCart().filter(x=>x.id!==rem.dataset.remove));renderCart()} const age=e.target.closest('[data-age]');if(age){const map={'0–3 months':'cloud-swaddle','3–6 months':'dream-sack','6–12 months':'moon-sleepwear'};location.href=`product.html?id=${map[age.dataset.age]||'cloud-swaddle'}`;} });
document.addEventListener('DOMContentLoaded',()=>{updateCount();renderProducts();renderProduct();renderCart();renderCheckout();const menu=document.querySelector('.menu');const nav=document.querySelector('nav');if(menu)menu.onclick=()=>nav.classList.toggle('mobile-open');});
